rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
  }, path: "users"

  resources :attendances, only: [:index, :new] do
    collection do
      get ":date", to: "attendances#show", as: "date"
      post "clock_in/:date", to: "attendances#clock_in", as: "clock_in"
      post "clock_out/:date", to: "attendances#clock_out", as: "clock_out"
    end
  end

  get "mypage", to: "users#show", as: "mypage"

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
  }, path: "admins"

  namespace :admins do
    root to: "dashboard#index"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :special_days, only: [:index, :new, :create, :destroy]
    resources :attendances, only: [:index]
  end

  root to: "attendances#index"

  get "/403", to: "errors#forbidden"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unprocessable_entity"
  get "/500", to: "errors#internal_server_error"

  match "*path", to: "errors#not_found", via: :all
end

rails/app/models/special_day.rb
class SpecialDay < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :description, presence: true, length: { maximum: 30 }
  validates :wage_increment, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :allowance, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validate :start_date_before_end_date
  validate :no_overlapping_dates

  def self.for_date(date)
    find_by("start_date <= ? AND end_date >= ?", date, date)
  end

  def self.in_month(date)
    start_date = date.beginning_of_month
    end_date = date.end_of_month
    where("start_date <= ? AND end_date >= ?", end_date, start_date)
  end

  private

    def start_date_before_end_date
      if start_date.present? && end_date.present?
        errors.add(:start_date, "は終了日より前でなければなりません") if start_date > end_date
        errors.add(:end_date, "は開始日より後でなければなりません") if end_date < start_date
      end
    end

    def no_overlapping_dates
      if SpecialDay.exists?(["(start_date <= ? AND end_date >= ?) OR (start_date <= ? AND end_date >= ?) OR (start_date >= ? AND end_date <= ?)", start_date,
                             start_date, end_date, end_date, start_date, end_date])
        errors.add(:base, "既存の特別日と日付が重複しています")
      end
    end
end

rails/app/controllers/admins/special_days_controller.rb
class Admins::SpecialDaysController < Admins::BaseController
  layout "admin"

  def index
    @special_days = SpecialDay.page(params[:page]).order("created_at DESC")
  end

  def new
    @special_day = SpecialDay.new
  end

  def create
    @special_day = SpecialDay.new(special_day_params)
    if @special_day.save
      redirect_to admins_special_days_url, notice: "特別日が作成されました"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @special_day = SpecialDay.find(params[:id])
    @special_day.destroy!

    redirect_to admins_special_days_url, notice: "特別日を削除しました", status: :see_other
  end

  private

    def special_day_params
      params.require(:special_day).permit(:start_date, :end_date, :description, :wage_increment, :allowance)
    end
end

rails/app/views/admins/special_days/index.html.erb
<% content_for(:title, "特別日一覧") %>

<div class="col-md-10 mx-auto">
  <div class="d-flex justify-content-between align-items-center">
    <h2 class="fw-bold">特別日</h2>
    <%= render "admins/shared/data_count", resources: @special_days %>
  </div>
  
  <table class="table">
    <thead>
      <tr>
        <th class="col-1">No</th>
        <th class="col-2">開始日</th>
        <th class="col-2">終了日</th>
        <th class="col-2">説明</th>
        <th class="col-2">時給加算額</th>
        <th class="col-2">手当</th>
        <th class="col-1"></th>
      </tr>
    </thead>
    <tbody>
      <% @special_days.each do |day|%>
        <tr>
          <td class="align-middle col-1"><%= day.id %></td>
          <td class="align-middle col-2"><%= day.start_date %></td>
          <td class="align-middle col-2"><%= day.end_date %></td>
          <td class="align-middle col-2"><%= day.description %></td>
          <td class="align-middle col-2"><%= number_to_currency(day.wage_increment) %></td>
          <td class="align-middle col-2"><%= number_to_currency(day.allowance) %></td>
          <td class="align-middle col-1">
            <%= link_to admins_special_day_path(day), data: { turbo_method: :delete, turbo_confirm: "特別日を削除します。よろしいですか？" }, class: "text-black" do %>
              <i class="bi bi-trash-fill"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class="mt-5 d-flex justify-content-center">
    <%= paginate @special_days, theme: 'bootstrap-5' %>
  </div>

  <div class="text-end">
    <%= link_to "特別日を追加する", new_admins_special_day_path %>
  </div>
</div>

rails/app/views/admins/special_days/new.html.erb
<% content_for(:title, "特別日作成") %>

<div class="row d-flex justify-content-center mt-5 px-3">
  <div class="col-md-6">
    <div class="d-flex justify-content-between align-items-center">
      <h2>特別日作成</h2>
    </div>
    <%= form_with model: @special_day, url: admins_special_days_path, local: true, class: 'mt-5' do |f| %>
      <%= render "layouts/error_messages", resource: @special_day %>
      <div class="form-group mt-4">
        <%= f.label :start_date, "開始日", class: 'form-label' %>
        <div class="d-flex align-items-end">
          <%= f.date_field :start_date, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group mt-4">
        <%= f.label :end_date, "終了日", class: 'form-label' %>
        <div class="d-flex align-items-end">
          <%= f.date_field :end_date, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group mt-4">
        <%= f.label :description, "説明" , class: 'form-label' %>
        <div class="d-flex align-items-end">
          <%= f.text_field :description, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group mt-4">
        <%= f.label :wage_increment, "時給加算額" , class: 'form-label' %>
        <div class="d-flex align-items-end">
          <%= f.number_field :wage_increment, min: 0, class: 'form-control' %>
          <span class="ml-2">円</span>  
        </div>
      </div>
      <div class="form-group mt-4">
        <%= f.label :allowance, "手当" , class: 'form-label' %>
        <div class="d-flex align-items-end">
          <%= f.number_field :allowance, min: 0, class: 'form-control' %>
          <span class="ml-2">円</span>  
        </div>
      </div>
      <div class="actions mt-5 text-center">
        <%= f.submit t('common.save'), class: 'btn btn-secondary col-4' %>
      </div>
    <% end %>
  </div>
</div>