rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
  }, path: "users"

  resources :attendances, only: [:index, :new] do
    collection do
      get ":date", to: "attendances#show", as: "date"
      post "clock_in/:date", to: "attendances#clock_in", as: "clock_in"
      post "clock_out/:date", to: "attendances#clock_out", as: "clock_out"
    end
  end

  get "mypage", to: "users#show", as: "mypage"

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
  }, path: "admins"

  namespace :admins do
    root to: "dashboard#index"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :special_days, only: [:index, :new, :create, :destroy]
    resources :attendances, only: [:index]
  end

  root to: "attendances#index"

  get "/403", to: "errors#forbidden"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unprocessable_entity"
  get "/500", to: "errors#internal_server_error"

  match "*path", to: "errors#not_found", via: :all
end

rails/app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" id="error_explanation" data-turbo-cache="false">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

rails/app/views/layouts/_flash_message.html.erb
<% flash.each do |key, message| %>
  <div class="alert <%= flash_class(key) %> text-center" role="alert">
    <%= message %>
  </div>
<% end %>

rails/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <a class="navbar-brand">勤怠管理</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-lg-0 text-center">
          <% if user_signed_in? || admin_signed_in? %>
            <li class="nav-item">
              <span class="nav-link">
                <%= username %>
              </span>
            </li>
            <% if !admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "マイページ", mypage_path, class: "nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= logout_link %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "アカウント登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

rails/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= page_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="d-flex flex-column min-vh-100">
  <div class="d-flex flex-grow-1">
    <aside class=" col-2 pt-5 flex-grow-1  d-flex flex-column h-100">
      <ul class="list-group list-group-flush pt-5">
        <li class="list-group-item">
          <span class="ms-3">
            <%= link_to "ホーム", admins_root_path %>
          </span>
        </li>
        <li class="list-group-item">
          <span class="ms-3">
            <%= link_to "ユーザー", admins_users_path %>
          </span>
        </li>
        <li class="list-group-item">
          <span class="ms-3">
            <%= link_to "勤怠管理", admins_attendances_path %>
          </span>
        </li>
        <li class="list-group-item">
          <span class="ms-3">
            <%= link_to "特別日", admins_special_days_path %>
          </span>
        </li>
      </ul>
    </aside>
    <div class="col-10 d-flex flex-column h-100">
      <%= render 'layouts/header' %>
      <%= render 'layouts/flash_message' %>
      <main class="main p-5 flex-grow-1">
        <div class="p-5 bg-white">
          <%= yield %>
        </div>
      </main>
    </div>
  </div>
</body>
</html>

rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <div class="container py-5">
      <%= yield %>
    </div>
  </body>
</html>