rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
    confirmations: "users/confirmations",
  }, path: "users"

  resources :attendances, only: [:index, :new] do
    collection do
      get ":date", to: "attendances#show", as: "date"
      post "clock_in/:date", to: "attendances#clock_in", as: "clock_in"
      post "clock_out/:date", to: "attendances#clock_out", as: "clock_out"
    end
  end

  get "mypage", to: "users#show", as: "mypage"

  devise_for :admins, controllers: {
    sessions: "admins/sessions",
  }, path: "admins"

  namespace :admins do
    root to: "dashboard#index"
    resources :users, only: [:index, :edit, :update, :destroy]
    resources :special_days, only: [:index, :new, :create, :destroy]
    resources :attendances, only: [:index]
  end

  root to: "attendances#index"

  get "/403", to: "errors#forbidden"
  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unprocessable_entity"
  get "/500", to: "errors#internal_server_error"

  match "*path", to: "errors#not_found", via: :all
end

rails/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user

  GUARANTEED_WAGE_MINUTES = 240
  OVERTIME_INTERVAL_MINUTES = 30

  def update_attendance_data
    update(
      working_minutes: calculate_working_minutes,
      overtime_minutes: calculate_overtime_minutes,
      total_working_minutes: calculate_total_working_minutes,
      hourly_wage: set_hourly_wage,
      daily_wage: calculate_daily_wage,
      overtime_pay: calculate_overtime_pay,
      allowance: set_allowance,
      transport_cost: TRANSPORT_COST,
      total_payment: calculate_daily_total_payment,
    )
  end

  def fetch_special_day
    @fetch_special_day ||= SpecialDay.for_date(date)
  end

  def special_day?
    fetch_special_day.present?
  end

  private

    def calculate_working_minutes
      total_working_minutes = calculate_total_working_minutes
      total_working_minutes - calculate_overtime_minutes
    end

    def calculate_overtime_minutes
      total_working_minutes = calculate_total_working_minutes
      [total_working_minutes - GUARANTEED_WAGE_MINUTES, 0].max
    end

    def calculate_total_working_minutes
      convert_seconds_to_minutes(clock_out_time - clock_in_time).to_i
    end

    def set_hourly_wage
      base_wage = weekend? ? user.wage.weekend_hourly_wage : user.wage.weekday_hourly_wage
      base_wage += fetch_special_day.wage_increment if special_day?
      base_wage
    end

    def weekend?
      [0, 6].include?(date.wday)
    end

    def calculate_daily_wage
      set_hourly_wage * convert_minutes_to_hour(GUARANTEED_WAGE_MINUTES)
    end

    def calculate_overtime_pay
      overtime_minutes = calculate_overtime_minutes
      half_hourly_wage = set_hourly_wage / 2
      (overtime_minutes >= OVERTIME_INTERVAL_MINUTES) ? (overtime_minutes / OVERTIME_INTERVAL_MINUTES) * half_hourly_wage : 0
    end

    def set_allowance
      special_day? ? fetch_special_day.allowance : allowance
    end

    def calculate_daily_total_payment
      calculate_daily_wage + calculate_overtime_pay + TRANSPORT_COST + allowance
    end

    def convert_minutes_to_hour(minutes)
      minutes / 60
    end

    def convert_seconds_to_minutes(seconds)
      seconds / 60
    end
end

rails/app/controllers/admins/attendances_controller.rb
class Admins::AttendancesController < Admins::BaseController
  def index
    @attendances = Attendance.preload(:user).page(params[:page]).order("created_at DESC")
  end
end

rails/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_attendance, only: [:show, :clock_in, :clock_out]

  def index
    @attended_dates = current_user.attended_dates
    target_month = AttendanceSummaryService.calculate_target_month(params[:start_date])
    @attendance_summary = AttendanceSummaryService.new(current_user, target_month)
    @start_date, @end_date = @attendance_summary.pay_period
    @special_days = SpecialDay.in_month(target_month)
  end

  def show
  end

  def clock_in
    @attendance.update!(clock_in_time: Time.current)
    flash[:notice] = "出勤しました"
    redirect_back(fallback_location: root_path)
  end

  def clock_out
    @attendance.update!(clock_out_time: Time.current)
    @attendance.update_attendance_data
    flash[:notice] = "退勤しました"
    redirect_back(fallback_location: root_path)
  end

  private

    def set_attendance
      @date = Date.parse(params[:date])
      @special_day = SpecialDay.for_date(@date)
      @attendance = Attendance.find_or_initialize_by(user_id: current_user.id, date: @date, special_day: @special_day.present?)
      logger.debug @attendance.special_day
    end
end

rails/app/views/attendances/index.html.erb
<% content_for(:title, "カレンダー") %>

<%= month_calendar do |date| %>
  <% special_day = @special_days.find { |sd| sd.start_date <= date && sd.end_date >= date } %>
  <%= link_to date_attendances_path(date: date), class: "calendar-link #{'attended' if @attended_dates.include?(date)} " do %>
    <%= date.day %>
    <%= special_day.description if special_day %>
  <% end %>
<% end %>

<div class="mt-5 w-50 mx-auto">
  <div class="mt-4 fs-3 fw-bold">
    <%= format_date(@start_date) %>
    ~
    <%= format_date(@end_date) %>
  </div>

  <dl class="mt-4">
    <h3>勤務日数</h3>
    <div class="d-flex">
      <dt class="col-8">平日勤務日数</dt>
      <dd class="col-4"><%= @attendance_summary.total_monthly_working_weekdays %>日</dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">土日・祝日勤務日数</dt>
      <dd class="col-4"><%= @attendance_summary.total_monthly_working_weekends %>日</dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">特別日勤務日数</dt>
      <dd class="col-4"><%= @attendance_summary.total_monthly_working_special_days %>日</dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">合計勤務日数</dt>
      <dd class="col-4"><%= @attendance_summary.total_monthly_working_days %>日</dd>
    </div>
  </dl>
  <dl class="mt-4">
    <h3>勤務時間</h3>
    <div class="d-flex">
      <dt class="col-8">平日勤務時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_weekday_working_minutes) %></dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">土日・祝日勤務時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_weekend_working_minutes) %></dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">特別日勤務時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_special_day_working_minutes) %></dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">合計勤務時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_working_minutes) %></dd>
    </div>
  </dl>
  <dl class="mt-4">
    <h3>残業時間</h3>
    <div class="d-flex">
      <dt class="col-8">平日残業時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_weekday_overtime_minutes) %></dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">土日・祝日残業時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_weekend_overtime_minutes) %></dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">特別日残業時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_special_day_overtime_minutes) %></dd>
    </div>
    <div class="d-flex">
      <dt class="col-8">合計残業時間</dt>
      <dd class="col-4"><%= convert_minutes_to_hour(@attendance_summary.total_monthly_overtime_minutes) %></dd>
    </div>
  </dl>
  <dl class="mt-4">
    <h3>基本給</h3>
    <div class="mt-2">
      <div class="d-flex">
        <dt class="col-8">平日基本給</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_weekday_daily_wage) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">土日・祝日基本給</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_weekend_daily_wage) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">特別日基本給</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_special_day_daily_wage) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">合計基本給</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_daily_wage) %></dd>
      </div>
    </div>
    <div class="mt-4">
      <h3>残業代</h3>
      <div class="d-flex">
        <dt class="col-8">平日残業代</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_weekday_overtime_pay) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">土日・祝日残業代</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_weekend_overtime_pay) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">特別日残業代</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_special_day_overtime_pay) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">合計残業代</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_overtime_pay) %></dd>
      </div>
    </div>
    <div class="mt-4">
      <div class="d-flex">
        <dt class="col-8">合計特別日手当</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_special_day_allowance) %></dd>
      </div>
      <div class="d-flex">
        <dt class="col-8">合計交通費</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_transport_cost) %></dd>
      </div>
    </div>
    <div class="mt-4">
      <div class="d-flex">
        <dt class="col-8">総支給額</dt>
        <dd class="col-4"><%= number_to_currency(@attendance_summary.total_monthly_payment) %></dd>
      </div>
    </div>
  </dl>
</div>

rails/app/views/attendances/show.html.erb
<% content_for(:title, "勤怠管理") %>

<div class="w-50 mx-auto">
  <div class="text-center">
    <div class="fs-4">
      <p><%= @attendance.date.strftime("%Y年%m月%d日") %> <%= @attendance.decorate.day_of_week(@date) %></p>
      <p><%= @special_day ? "#{@special_day.description}（特別日）" : "" %></p>
    </div>
    <% if @attendance.decorate.today? %>
      <div class="clock fs-1"></div>
      <div class="d-flex justify-content-around mt-3">
        <%= button_to "出勤", clock_in_attendances_path(date: @date), method: :post, class: 'btn btn-lg btn-success', disabled: !@attendance.decorate.can_clock_in? %>
        <%= button_to "退勤", clock_out_attendances_path(date: @date), method: :post, class: 'btn btn-lg btn-danger', disabled: !@attendance.decorate.can_clock_out? %>
      </div>
    <% end %>
  </div>
  
  <% if @attendance.clock_in_time.present? %>
    <div class="mt-5">
      <dl class="">
        <div class="d-flex">
          <dt class="col-6">出勤時間</dt>
          <dd class="col-6"><%= format_time_only(@attendance.clock_in_time) %></dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">退勤時間</dt>
          <dd class="col-6"><%= format_time_only(@attendance.clock_out_time) %></dd>
        </div>
      </dl>
      <dl class="">
        <div class="d-flex">
          <dt class="col-6">勤務時間</dt>
          <dd class="col-6"><%= convert_minutes_to_hour(@attendance.working_minutes) %></dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">残業時間</dt>
          <dd class="col-6"><%= convert_minutes_to_hour(@attendance.overtime_minutes) %></dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">総勤務時間</dt>
          <dd class="col-6"><%= convert_minutes_to_hour(@attendance.total_working_minutes) %></dd>
        </div>
      </dl>
      <dl class="">
        <div class="d-flex">
          <dt class="col-6">時給</dt>
          <dd class="col-6">
            <%= number_to_currency(@attendance.hourly_wage) %>
          </dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">支給額</dt>
          <dd class="col-6">
            <%= number_to_currency(@attendance.daily_wage) %>
          </dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">残業代</dt>
          <dd class="col-6">
            <%= number_to_currency(@attendance.overtime_pay) %>
          </dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">交通費</dt>
          <dd class="col-6">
            <%= number_to_currency(TRANSPORT_COST) %>
          </dd>
        </div>
        <div class="d-flex">
          <dt class="col-6">特別日手当</dt>
          <dd class="col-6">
            <%= number_to_currency(@attendance.allowance) %>
          </dd>
        </div>
      </dl>
      <dl class="">
        <div class="d-flex">
          <dt class="col-6">総支給額</dt>
          <dd class="col-6">
            <%= number_to_currency(@attendance.total_payment) %>
          </dd>
        </div>
      </dl>
    </div>
  <% else %>
    <div class="mt-5 text-center">
      <p class="fs-3">出勤データがありません</p>
    </div>
  <% end %>
</div>